### ISSUE TITLE
[Request] config size change

### ISSUE THREAD

**Issue by RavenknightDM** [paulo-roger/flying-tokens#1]
Hiya, thanks for the mod. Looks really nice but would it be possible to add an option to not change the size of the token? It screws up the maps too much for me and makes it hard to tell people which squares that the enemies are in. Other then that, solid work and thanks for sharing.

**Comment by roi007leaf** [comment]
@paulo-roger https://github.com/paulo-roger/flying-tokens/pull/2/ :)

**Comment by paulo-roger** [comment]
Included in the new release.
Thank you guys!
