### ISSUE TITLE
FEATURE REQUEST: change token image

### ISSUE THREAD

**Issue by pesky-wobbit** [paulo-roger/flying-tokens#6]
I could manually change the image, but would be nice if there were a field to automate the change. 

Example: Griffon with wings tucked to Flying Griffon with wings spread.

Great mod. Thanks!

**Comment by paulo-roger** [comment]
Nice idea! would you mind to lend these 2 tokens for a test?

**Comment by paulo-roger** [comment]
Added in the new version
https://github.com/LeafWulf/flying-tokens

**Comment by pesky-wobbit** [comment]
Was just about to send you 2 tokens to test, but you've done it already.
Works well. Thank you!!!

**Comment by paulo-roger** [comment]
please do, I would like to add some screenshots of the feature

**Comment by pesky-wobbit** [comment]
The attached tokens are from Forgotten Adventures creature tokens 35
<https://www.forgotten-adventures.net/product/tokens/creatures/creature-tokens-pack-35/>.
It's a free pack, but you probably should credit them. Thanks for the great
mod!

**Comment by paulo-roger** [comment]
Thanks! :)
