### ISSUE TITLE
FEATURE REQUEST: Adjustable rate of scaling

### ISSUE THREAD

**Issue by justinrpurdy** [paulo-roger/flying-tokens#7]
I played my first session with this module last night, and it was really cool - except I had to keep adjusting the token scaling because the tokens became enormous. A setting along the lines of "adjust scale by x for every 10' of elevation change" would make it much more usable. Thanks!

**Comment by paulo-roger** [comment]
Yeah it is coming in the next version!
I also think the scale is kinda messed

**Comment by paulo-roger** [comment]
Added in the new version
https://github.com/LeafWulf/flying-tokens
